//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace library_2121.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.borrow = new HashSet<borrow>();
        }
    
        public string tsbh { get; set; }
        public string fenlei { get; set; }
        public string shuming { get; set; }
        public string zuozhe { get; set; }
        public string chubanhse { get; set; }
        public System.DateTime chubanriqi { get; set; }
        public double dingjia { get; set; }
        public System.DateTime rkrq { get; set; }
        public string zt { get; set; }
        public string sfwz { get; set; }
        public string beizhu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrow> borrow { get; set; }
        public virtual yuyue yuyue { get; set; }
    }
}
