//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace library_2121.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrow
    {
        public int ID { get; set; }
        public string tsbh { get; set; }
        public string shuming { get; set; }
        public string jszh { get; set; }
        public string name { get; set; }
        public System.DateTime jsrq { get; set; }
        public Nullable<System.DateTime> hsrq { get; set; }
        public string zt { get; set; }
        public double fkje { get; set; }
        public Nullable<System.DateTime> hssj { get; set; }
    
        public virtual book book { get; set; }
        public virtual reader reader { get; set; }
    }
}
