//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace library_2121.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class open1
    {
        public string user_name { get; set; }
        public string password { get; set; }
        public string jibie { get; set; }
        public string name { get; set; }
        public string card { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> cjsj { get; set; }
    }
}
