//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace library_2121.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class reader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reader()
        {
            this.borrow = new HashSet<borrow>();
        }
    
        public string jszh { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string danwei { get; set; }
        public string jibie { get; set; }
        public int yjss { get; set; }
        public System.DateTime djrq { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string guashi { get; set; }
        public int gqfk { get; set; }
        public int jieshuzongshu { get; set; }
        public int jsts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrow> borrow { get; set; }
    }
}
